# Generated by Django 3.2.7 on 2021-11-15 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20211111_0100'),
        ('users', '0011_auto_20211111_0100'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('hasBeenRead', models.BooleanField(default=False)),
                ('date', models.DateTimeField()),
                ('fromUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fromUser', to=settings.AUTH_USER_MODEL)),
                ('toUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BidNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('hasBeenRead', models.BooleanField(default=False)),
                ('date', models.DateTimeField()),
                ('fromBidProduct', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.bidproduct')),
                ('toUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
