# Generated by Django 4.1.dev20210924165208 on 2021-11-20 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_bidnotification_usernotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='money',
            field=models.FloatField(blank=True, default=0, max_length=50),
        ),
    ]
