# Generated by Django 3.2.7 on 2021-11-25 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_systemnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemnotification',
            name='image',
            field=models.ImageField(blank=True, default='pic_default.jpg', null=True, upload_to=''),
        ),
    ]
