# Generated by Django 3.2.5 on 2021-10-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=50)),
                ('price', models.FloatField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('condition', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('currentBid', models.CharField(max_length=50)),
            ],
        ),
    ]
