# Generated by Django 3.2.7 on 2021-11-05 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20211105_1603'),
        ('store', '0002_auto_20211105_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidproduct',
            name='bidWinner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.bid'),
        ),
    ]
