# Generated by Django 3.2.7 on 2021-11-11 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0004_bidproduct_createdby_bidproduct_isactive_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidproduct',
            name='createdBy',
        ),
        migrations.RemoveField(
            model_name='stockproduct',
            name='createdBy',
        ),
        migrations.AddField(
            model_name='bidproduct',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockproduct',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bidproduct',
            name='bidWinner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='BidWinner', to=settings.AUTH_USER_MODEL),
        ),
    ]
