# Generated by Django 3.2.7 on 2021-11-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_bidproduct_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidproduct',
            name='condition',
            field=models.CharField(choices=[('bad', 'BAD'), ('good', 'GOOD'), ('like new', 'LIKE NEW'), ('new', 'NEW')], default='good', max_length=20),
        ),
    ]
