# Generated by Django 4.1.dev20210924165208 on 2021-11-24 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_stockproduct_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidproduct',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
