# Generated by Django 4.1.dev20210924165208 on 2021-11-19 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='totalPaid',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.FloatField(max_length=50),
        ),
    ]
