# Generated by Django 4.1.dev20210924165208 on 2021-11-20 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_order_totalpaid_alter_orderitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.FloatField(default=1.0, max_length=50),
        ),
    ]
