# Generated by Django 4.1.dev20210924165208 on 2021-11-20 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_bidproduct_currentbid_alter_bidproduct_minbid'),
        ('cart', '0003_alter_orderitem_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid', to='cart.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidProduct', to='store.bidproduct')),
            ],
        ),
    ]
