# Generated by Django 4.1.dev20210924165208 on 2021-11-20 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_orderbid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbid',
            name='price',
            field=models.FloatField(default=1.0, max_length=50),
        ),
    ]
